# Generated by Django 4.0.6 on 2022-07-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='имя')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='test_api.person', verbose_name='хозяин')),
            ],
            options={
                'verbose_name': 'петомец',
                'verbose_name_plural': 'петомцы',
                'ordering': ['owner_id', 'name'],
                'unique_together': {('name', 'owner')},
            },
        ),
    ]
